replicaCount: 2

image:
  repository: docker.io/zerozonez/java-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30007

serviceMonitor:
  enabled: true
  namespace: monitoring
  releaseLabel: monitoring
  interval: 15s

resources: {}
