{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "java-app.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    release: {{ .Values.serviceMonitor.releaseLabel }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "java-app.name" . }}
  endpoints:
  - port: metrics
    path: /actuator/prometheus
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
