apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}-service
  labels:
    app: {{ include "java-app.name" . }}
    release: {{ .Values.serviceMonitor.releaseLabel }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "java-app.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
    - name: metrics
      port: {{ .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
